name: Weather Forecast Pipeline

on:

  # Manual Run
  workflow_dispatch:

  # Daily Automatic Run
  schedule:
    - cron: "45 13 * * *"   # 7:15 PM IST

jobs:

  weather-pipeline:

    runs-on: ubuntu-latest

    steps:

      # -----------------------------------
      # 1. Checkout Repository
      # -----------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -----------------------------------
      # 2. Setup Python
      # -----------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # -----------------------------------
      # 3. Upgrade pip
      # -----------------------------------
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # -----------------------------------
      # 4. Install Requirements
      # -----------------------------------
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # -----------------------------------
      # 5. Run Weather API Extraction
      # -----------------------------------
      - name: Extract Weather Data
        run: python -m crs.extract.extract_api

      # -----------------------------------
      # 6. Run Data Transformation
      # -----------------------------------
      - name: Transform Weather Data
        run: python -m crs.transform.transform_csv

      # -----------------------------------
      # 7. Run Forecast Prediction
      # -----------------------------------
      - name: Generate Forecast
        run: python -m crs.model.predict

      # -----------------------------------
      # 8. Commit Updated Files
      # -----------------------------------
      - name: Commit and Push Forecast Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/
          git add logs/

          git commit -m "Auto update forecast data" || echo "No changes to commit"

          git push